### ISSUE TITLE
Not working with Berkshelf

### ISSUE THREAD

**Issue by tb01923** [cgravier/selfsigned_certificate#4]
when I add the cookbook to berself I am getting an "unknown compression type" error. Removing the dependency removes the error.

Installing selfsigned_certificate (0.1.0)
Using sudo (2.7.1)
Using users (1.8.2)
Using windows (1.36.6)
Using yum (3.6.0)
Using yum-epel (0.6.0)
Using zookeeper (2.6.0)
E, [2015-05-13T12:28:20.076060 #23224] ERROR -- : Actor crashed!
Berkshelf::UnknownCompressionType: The file at '/home/tbrown/chef-repo/community-rest-stream20150513-23224-1wwblxi' is not a known compression type
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:19:in `unpack'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/community_rest.rb:105:in`download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:62:in `try_download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:36:in`block in download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in `each'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/downloader.rb:35:in`download'
    /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:105:in `install'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in`public_send'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:26:in `dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/calls.rb:63:in`dispatch'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:60:in `block in invoke'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/cell.rb:71:in`block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in`block in initialize'
    /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
The file at '/home/tbrown/chef-repo/community-rest-stream20150513-23224-1wwblxi' is not a known compression type

**Comment by mbman** [comment]
It's because the package was uploaded to Opscode in .zip format: https://supermarket.chef.io/api/v1/cookbooks/selfsigned_certificate/versions/0.1.0/download
The author needs to upload a .tar version
